---
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract zipped artifact
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: home/ubuntu/backend

- name: Start Application
  shell: |
    npm install
    cd /home/ubuntu/backend 
    pm2 stop backend
    pm2 start npm --name "backend" -- start